export const Comedy = [
    {
        id: 0,
        title: 'GoodWill Hunting',
        subhead: 'scene in garden',
        actor: 'Robin Williams',
        image: "/assets/images/goodwill.png",
        movie: "/GoodWill",
        speech: ['Noun', 'City or Town', 'Famous Publication',
            'adverb', 'Famous Person', 'Hobby', 'Place', 'Noun',
            'Plural Noun', 'Verb Past Tense', 'Noun', 'Emotion',
            'Adjective', 'Plural Object', 'Noun', 'Famous Rapper',
            'Noun', 'Adjective', 'Verb', 'Body Part', 'Diety', 'Noun',
            'Place', 'Emotion', 'Disease', 'Furniture', 'Body Part', 'Famous Saying',
            'Noun', 'Adjective', 'Adjective', 'Adjective', 'Adjective', 'Noun',
            'Name', 'Object', 'Object', 'Zodiac Sign', 'Famous Book', 'Noun',
            'Famous Publication', 'Famous TV Show', 'Condescending Nickname',
            'Plural Animal'
        ],
        words: [],
        currentWord: [],
        complete: ["You know what occured to me? You're just a ",
            ". You don't have the faintest idea what you're talking about. You've never been out of ",
            ". So if I asked you about art, you'd probably give me the skinny on every ",
            " ever written. ",
            ", You know a lot about him.  Life's work, political aspirations, ",
            ", the whole works, right? But i bet you can't tell me what it smells like in ",
            ". You've never actually stood there, looked up at that beautiful ",
            ". If I asked you about ",
            ", you'd probably give me a syllabus of your personal favorites. You may have even ",
            " a few times. But you can't tell me what it feels like to wake  up next to a ",
            " and feel truly ",
            ". You're a ",
            " kid. If i asked you about war, you'd probably throw ",
            " at me, right? But you've never been near one. You've never held your best friend's ",
            " in your lap, and watched him gasp his last breath and look to you for help. If I asked you about love, you'd probably quote me ",
            ".  But you've never looked at a ",
            " and been totally ",
            ". Knowing someone that could ",
            " you with her ",
            ". Feeling like ",
            " put a ",
            " on Earth just for you. That could rescue you from the depthes of ",
            ". And you wouldn't know what its like to be her ",
            ". To have that ",
            " for her be there forever through anything, through ",
            ". And you wouldn't know about sleeping sitting up in a ",
            " for two monthes holding her ",
            " because the doctors could see in your eyes that the terms, ",
            " don't apply to you. You dont know about real loss. Because that only occurs when you love ",
            " more than you love yourself. I doubt you've ever dared to love anything that much. I look at you, I don't see a ",
            ", ",
            " man. I see a ",
            ", ",
            " kid. But you're a ",
            ", ",
            ". Nobody denies that. Noone could possibly understand the depthes of you. But you presumed to know everything about me because you saw a ",
            " of mine and you ripped my ",
            " apart. You're a ",
            ", right? Do you think I know the first thing about how hard your life has been, how you feel, who you are because I read ",
            "? Does that incapsulate you? Personally I don't give a ",
            " about that because I cant learn anything from you I can't read in ",
            ". Unless you want to talk about ",
            ". Then im fascinated, im in. But you don't want to do that do ya, ",
            ". You'd be terrified of ",
            ". Your move, ",
            "."]
    },
    {
        id: 1,
        title: 'Wedding Crashers',
        subhead: 'scene at the table',
        actor: 'Vince Vaughn',
        image: '/assets/images/bars.png',
        movie: "/Wedding",
        speech: ['Mythical Creature', 'Verb', 'Objects Plural', 'adverb','Famous Person', 'Occupation Plural','Condiment','Article of Clothing',
        'Animal','Mental State','Name','Adjective describing Person','Name','Small Animal','Small Object','VideoGame','TV Character','Adjective',
        'Emotion','Occupation', 'Disease', 
    ],
        words: [],
        currentWord: [],
        complete: ['She\'s good. I mean, I believed that she was a ', ' and it hurts to ', 'But I, you know, was looking to take',
        ', so could I really feel that bad?  It\'s not like I was', 'You know what I\'m saying? So fair play. And let\'s be ',
        ', okay? Let\'s put all the','on the table. She\'s fit for a',', this','three ways towards the weekend, and you want to know what? I dig it!',
        'Because you want to know what the kicker is, ','Maybe I\'m a little','That\'s right, maybe ',' is a little nuts! And there\'s something about me that I\'m a little ',
        '. I know it\'s a surprise. I know it\'s not on the surface. Man, I had a little ',' when I was a kid. His name was ','Famous Person',
        '. We used to play ','everyday and bless his heart, ','would always let me win. And that ain\'t ','! There\'s something odd in that, but maybe that\'s what it takes to make you feel',
        '. I don\'t know! But I know when that ', ' starts getting kooky, there\'s something about me that feels ', ' inside.'
        ]
    },
    {
        id: 2,
        title: 'Talladega Nights',
        subhead: 'scene at restaurant',
        actor: 'Amy Adams',
        image: '/assets/images/bars.png',
        movie: "/Talladega",
        speech: ['Verb', 'Name', 'Noun (NameCalling)', 'Verb (ing)', 'Celebrity', 'Noun', 'Verb','Verb', 'Food or Beverage', 'Verb', 'Country', 'Country',
        'Politician' , "Desert", 'Verb', "Number", "Fantasy Animal", "State", "Name", "Celebrity", "Food" 
        
    ],
        words: [],
        currentWord: [],
        complete: ['Do you want to know, why I think you should ', ', ', '? It\'s because it\'s what you love, ',
        ' It is who you were born to be. And here you sit, ', '. Well, ', ' is not a thinker.  He is a ' , 
        '. nd that\'s what you need to do. You don\'t need to ', '. You need to ', '. You need ','. You need to go out there, and you need to ',
        ' You need to grab a hold of that line between ', " and ", ", and you need to wrestle " , 'to the ground like a demon cobra! And then, when ',
        ' rises up in your belly, you ', '. And you know that fear is powerful, because it has been there for ', 'years. And it is good. And you use it. And you ride it; you ride it like a ',
        'through the gates of ', ', and then you win, ' , '. You WIN! And you don\'t win for anybody else. You win for ', ', you know why? Because a man takes','. He takes it all. And you\'re a man, aren\'t you? Aren\'t you? '

    ]
    },
    {
        id: 3,
        title: 'Lizzy Caplan',
        subhead: 'scene at the party',
        actor: 'Woody Allen',
        image: '/assets/images/bars.png',
        movie: "/Annie",
        speech: ['Famous Event', 'Adjective', 'Noun', 'Emotion', 'Beverage (Plural)', 'Band', 'Liquid', 'Politician', 'Emotion',
        'City or Town', 'Animal (Plural)', 'Animal (Plural)', 'Occupation (Plural)', 'Type of Food', 'Famous Author', 'Famous Actress',
        'Type of Cuisine', 'Name', "Noun (Name Calling)"
    ],
        words: [],
        currentWord: [],
        complete: ['Explain what?? How you forgot to invite us to ', '> Buddy, you\'re not pretending any more. You\'re ', 
        'Cold, shiny, hard ', '. Did you have a ', ' time? Did you drink awesome ', ' and listen to ', ' and soak up each other\'s ',
        'God, ya know, at least me and ', ' know we\'re mean! You try to act like you\'re so ', ' like "Oh. I used to live in ',
        ' and play with all the little ', ' and all the little ', 'That is the thing with you ','! You think that everybody is in love with you when actually everybody hates ',
        ' like ... ', ' for example. He broke up with ', ' and he still doesn\'t want you. So why are you still messing with ', '? I\'ll tell you why! Cause you are a mean girl, ',
        '. You\'re a ','!'
    ]
    }
];