export const Drama = [
    {
        id: 0,
        title: 'GoodWill Hunting',
        subhead: 'scene in garden',
        actor: 'Robin Williams',
        image: "/assets/images/goodwill.png",
        movie: "/GoodWill",
        speech: ['Noun', 'City or Town', 'Famous Publication',
            'adverb', 'Famous Person', 'Hobby', 'Place', 'Noun',
            'Plural Noun', 'Verb Past Tense', 'Noun', 'Emotion',
            'Adjective', 'Plural Object', 'Noun', 'Famous Rapper',
            'Noun', 'Adjective', 'Verb', 'Body Part', 'Diety', 'Noun',
            'Place', 'Emotion', 'Disease', 'Furniture', 'Body Part', 'Famous Saying',
            'Noun', 'Adjective', 'Adjective', 'Adjective', 'Adjective', 'Noun',
            'Name', 'Object', 'Object', 'Zodiac Sign', 'Famous Book', 'Noun',
            'Famous Publication', 'Famous TV Show', 'Condescending Nickname',
            'Plural Animal'
        ],
        words: [],
        currentWord: [],
        complete: ["You know what occured to me? You're just a ",
            ". You don't have the faintest idea what you're talking about. You've never been out of ",
            ". So if I asked you about art, you'd probably give me the skinny on every ",
            " ever written. ",
            ", You know a lot about him.  Life's work, political aspirations, ",
            ", the whole works, right? But i bet you can't tell me what it smells like in ",
            ". You've never actually stood there, looked up at that beautiful ",
            ". If I asked you about ",
            ", you'd probably give me a syllabus of your personal favorites. You may have even ",
            " a few times. But you can't tell me what it feels like to wake  up next to a ",
            " and feel truly ",
            ". You're a ",
            " kid. If i asked you about war, you'd probably throw ",
            " at me, right? But you've never been near one. You've never held your best friend's ",
            " in your lap, and watched him gasp his last breath and look to you for help. If I asked you about love, you'd probably quote me ",
            ".  But you've never looked at a ",
            " and been totally ",
            ". Knowing someone that could ",
            " you with her ",
            ". Feeling like ",
            " put a ",
            " on Earth just for you. That could rescue you from the depthes of ",
            ". And you wouldn't know what its like to be her ",
            ". To have that ",
            " for her be there forever through anything, through ",
            ". And you wouldn't know about sleeping sitting up in a ",
            " for two monthes holding her ",
            " because the doctors could see in your eyes that the terms, ",
            " don't apply to you. You dont know about real loss. Because that only occurs when you love ",
            " more than you love yourself. I doubt you've ever dared to love anything that much. I look at you, I don't see a ",
            ", ",
            " man. I see a ",
            ", ",
            " kid. But you're a ",
            ", ",
            ". Nobody denies that. Noone could possibly understand the depthes of you. But you presumed to know everything about me because you saw a ",
            " of mine and you ripped my ",
            " apart. You're a ",
            ", right? Do you think I know the first thing about how hard your life has been, how you feel, who you are because I read ",
            "? Does that incapsulate you? Personally I don't give a ",
            " about that because I cant learn anything from you I can't read in ",
            ". Unless you want to talk about ",
            ". Then im fascinated, im in. But you don't want to do that do ya, ",
            ". You'd be terrified of ",
            ". Your move, ",
            "."]
    },
    {
        id: 1,
        title: 'ShawShank Redemption',
        subhead: 'Speech During Outro',
        actor: 'Morgan Freeman',
        image: '/assets/images/bars.png',
        movie: "/Wedding",
        speech: ['Household Task (ing)', 'Adjective','Crime','Object Plural', 'Noun (Name Calling)','Emotion','Verb(Mundane Task)',
        'Verb(Recreational Activity)', 'Adjective', 'TV Series',' City or State', 'Reality TV Star', 'Body of Water', 'Adjective',

    ],
        words: [],
        currentWord: [],
        complete: ['Get busy livin\' or get busy','. That\'s ','For the second time in my life, I am guilty of ','Of course, I doubt they\'ll toss up any ',
        ' for that. Not for an old ',' like me... I find I\'m so ',' I can barely ',' or ', '  I think it\'s the excitement only a ',
        'man can feel, a free man at the start of ',' whose conclusion is uncertain. I hope I can make it across  ', '  I hope to see ',
        ' shake his hand. I hope the ','  is as ', ' as it has been in my dreams. I hope.'
        ]
    },
    {
        id: 2,
        title: 'Requiem for a Dream ',
        subhead: 'Red Dress Monologue',
        actor: 'Ellen Burstyn ',
        image: '/assets/images/bars.png',
        movie: "/Talladega",
        speech: ['Method of Transportation', 'Body Part','Noun (Name Calling)','TV Show', 'Verb','Famous Actor',
        'Object Plural','Body Part (Plural)','Musical Instrument', 'TV Host','Verb (Recreational Activity)','Name',
        'Adjective', 'Adjective'
        ],
        words: [],
        currentWord: [],
        complete: [ ' Big deal? You drove up in a ', '. Did you see who had the best ','I\'m somebody now, ','. Everybody likes',
        'Soon, ',' people will see me and they\'ll all ',' I\'ll tell them about you, ',', how good he was to us. Remember? It\'s a reason to get',
        ' in the morning. It\'s a reason to lose ','. To fit in a ',' why should I? I\'m alone. ', '\'s gone. ','. You\'re gone. I\'ve no one to...',
        ' for. What have I got, ','? ......I\'m ', '. I\'m ','.'

    ]
    },
    {
        id: 3,
        title: 'Rocky Balboa',
        subhead: 'scene at the party',
        actor: 'Sylvester Stallone',
        image: '/assets/images/bars.png',
        movie: "/Annie",
        speech: ['Authority Figure(Generic)', 'Occupation', 'Famous Performer','Adjective', 'TV Show','Famous Athlete','Verb (Past Tense)',
        'Emotion', 'Body Part','Famous Politician','Large Animal','Popular Saying', 'Nice Thing (Plural)', 'Nice Thing (Plural)', 'Adjective',
        'Body Part (Plural)', 'Olde Time Actor','Verb (Recreational Activity)', ' Verb (Recreational Activity)','Type of Quisine','Object (Plural)',
        'Celebrity', 'Politician', 'Fantasy Animal (Plural)', 'TV Show', 'Type of Relationship','Famous Organization','Famous Rapper'
    ],
        words: [],
        currentWord: [],
        complete: ['You used to fit right here. I’d hold you up to say to your', ' This kid’s going to be the best ', ' in the world. This kid’s going to be somebody better than ',
        '. And you grew up good and ',', it was great just watching ','everyday, it was like a privilege. Til the time come for you to be your own man and take on ',
        ' and you did. But somewhere along the line you ','. You stopped being ','. You let people stick a ',' in your face and tell you you’re no good; and when things got hard you started looking for ',
        ' to blame, like a big ','. Let me tell you something you already know. ','The world ain’t all ',' and ','.  It’s a very mean and nasty place and I don’t care how ',
        ' you are it will beat you to your ', '  and keep you there permanently if you let it. You, me or nobody is gonna hit as hard as ',
        '. But it ain’t about how hard you hit. It’s about how hard you can ', 'and keep moving forward; how much you can ',' and keep moving forward. That’s how winning is done! Now if you know what you’re worth then go out and get ',
        '. But you gotta be willing to take ', ', and not pointing fingers sayin’ you ain’t what you wanna be because of ',' or ', 'Or anybody!',
        's do that and that ain’t you! You’re better than that! I’m always going to love ', 'no matter what. No matter what happens. You’re my ',
        'and you’re my blood. You’re the best thing in ',' But until you start believing in ','you ain’t gonna have a life.'
    ]
    }
];